FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && \
    apt-get install -y -qq python3 python3-pip git openssh-client && \
    pip3 install -q cryptography pytest && \
    git config --global init.defaultBranch master && \
    git config --global user.email "ci@test.com" && \
    git config --global user.name "CI"
